const express = require('express');
const { authUser } = require('../middleware/auth');
const { adminOnly } = require('../middleware/adminOnly');
const controller = require('../controllers/order.controller');
const router = express.Router();
router.post('/', authUser, controller.createOrder);
router.get('/me', authUser, controller.getMyOrders);
router.get('/', authUser, adminOnly, controller.getAllOrders);
router.get('/stats', authUser, adminOnly, controller.getOrderStats);
router.get('/:id', authUser, controller.getOrderById);
router.patch('/:id/status', authUser, adminOnly, controller.updateStatus);
module.exports = router;
