import { useEffect, useState } from 'react';
import { getDashboardStats } from '../../src/api/dashboard.api';
import StatCard from '../../src/components/admin/StatCard';
import AdminPanel from '../../src/components/admin/AdminPanel';
import AdminTable from '../../src/components/admin/AdminTable';
import AdminBadge from '../../src/components/admin/AdminBadge';
import RevenueTrendChart from '../../src/components/admin/charts/RevenueTrendChart';
import CategoryDonutChart from '../../src/components/admin/charts/CategoryDonutChart';
const money = (value) => `฿${Number(value || 0).toLocaleString()}`;
export default function AdminDashboard() { const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { getDashboardStats().then(setData).catch((e) => setError(e.message)); }, []); if (error) return <p className="page-message">{error}</p>; if (!data) return <p className="page-message">Loading dashboard…</p>; const { stats, revenueTrend, salesByCategory, lowStock, recentOrders } = data; return <div className="admin-page"><div className="stat-grid"><StatCard label="Total Revenue" value={money(stats.totalRevenue)} /><StatCard label="Total Orders" value={stats.totalOrders} /><StatCard label="Total Products" value={stats.totalProducts} /><StatCard dark label="Low Stock Alert" value={stats.lowStockCount} note="Items with 10 or fewer units" /></div><div className="dashboard-grid"><AdminPanel title="Revenue Trend"><RevenueTrendChart data={revenueTrend} /></AdminPanel><AdminPanel title="Sales by Category"><CategoryDonutChart data={salesByCategory} /></AdminPanel></div><div className="dashboard-grid"><AdminPanel title="Low Stock Inventory"><AdminTable columns={['Product', 'Artist', 'In stock']} >{lowStock.map((item) => <tr key={item._id}><td>{item.name}</td><td>{item.artist?.name || '—'}</td><td>{item.quantity}</td></tr>)}</AdminTable></AdminPanel><AdminPanel title="Recent Orders"><AdminTable columns={['Order', 'Customer', 'Total', 'Status']} >{recentOrders.map((item) => <tr key={item._id}><td>#{item._id.slice(-6)}</td><td>{item.userId ? `${item.userId.firstName} ${item.userId.lastName}` : '—'}</td><td>{money(item.totalAmount)}</td><td><AdminBadge status={item.status} /></td></tr>)}</AdminTable></AdminPanel></div></div>; }
